---
- name: configure /etc/hostname
  hostname:
    name: "{{ ansible_hostname }}.{{ ansible_domain }}"
  become: true
  tags: hosts

- name: configure /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  become: true
  tags: hosts
